apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: ngis:
      - containerPort: 80
